#!/bin/sh

pkg upgrade
pkg autoremove
pkg clean -y
pkg version -qo -Rl '?'
pkg annotate -a -S deprecated
pkg annotate -a -S expiration_date
pkg audit

jail_update() {
	jail="${1}"
	name="${jail##*/}"
	printf "\n%s:\n" "${name}"
	jexec "${name}" pkg upgrade
	jexec "${name}" pkg autoremove
	jexec "${name}" pkg clean -a -y
	jexec "${name}" pkg version -qo -Rl '?'
	jexec "${name}" pkg annotate -a -S deprecated
	jexec "${name}" pkg annotate -a -S expiration_date
	jexec "${name}" pkg audit
}

chroot_update() {
	jail="${1}"
	name="${jail##*/}"
	printf "\n%s:\n" "${name}"
	if test ! -f "${jail}/var/db/pkg/local.sqlite"
	then
		return
	fi
	chroot "${jail}" pkg upgrade
	chroot "${jail}" pkg autoremove
	chroot "${jail}" pkg clean -a -y
	chroot "${jail}" pkg version -qo -Rl '?'
	chroot "${jail}" pkg annotate -a -S deprecated
	chroot "${jail}" pkg annotate -a -S expiration_date
	chroot "${jail}" pkg audit
}

find_jail() {
	name=`jls -n | fgrep " path=${jail} " | tr ' ' '\n' | grep "^name="`
	name="${name#name=}"
	case "${name}" in
	'')
		chroot_update "${jail}"
		;;
	*)
		jail_update "${name}"
		;;
	esac
}

list=""
case "${1}" in
'')
	cd /
	listfile="/usr/local/etc/jails.txt"
	if test -f "${listfile}"
	then
		list=`grep -v "^#" "${listfile}"`
		break
	fi
	ARCH=`make -V MACHINE_ARCH`
	HOST=`hostname -s`"-${ARCH}"
	listfile="/usr/src/jails-${HOST}.txt"
	if test -f "${listfile}"
	then
		list=`grep -v "^#" "${listfile}"`
		break
	fi
	;;
*)
	list="${@}"
	;;
esac

for jail in ${list}
do
	find_jail "${jail}"
done

# eof
